# Generated by Django 4.2 on 2023-04-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genres', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='moviesapp.collection')),
            ],
        ),
    ]
